#!/usr/bin/env bash

export CONTECO_LABEL="external.streamsets - ContEco"
export CONTECO_DESCRIPTION="Streamsets Datacollector image with ContEco external prerequisites installed."

export CONTECO_TYPE="external"
export CONTECO_NAME="streamsets"
export CONTECO_TAG="3.16.0"

export CONTECO_BASE="streamsets/datacollector:3.16.0"
export CONTECO_BUILD="external-mapped"
